version: "3.9"
services:
  db_dish:
    image: postgres
    container_name: db_dish
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dish
      - PGDATA=/var/lib/postgresql/data
#    volumes:
#      - /home/sergey/projects/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
  app:
    build:
      context: .
      dockerfile: ./dish/Dockerfile
    image: dish
    container_name: dish
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_dish:5432/dish
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - 127.0.0.1:80:8080
    depends_on:
      - db_dish
